# Permalinks
permalink:        pretty
relative_permalinks: false

title:            FINN Technology
tagline:          <a href="//finn.no/apply-here">Join us?</a>
url:              ""
paginate:         1
paginate_path:    "page/:num"
google_analytics_id: UA-32205740-1
baseurl:          /
author:
  name:           Finn Technology
  url:            https://finn.no/
  twitter:        FINN_tech
  email:          tech@finn.no

# Custom vars
markdown: kramdown
kramdown:
  input: GFM
exclude: [vendor]
version:          0.0.1
github:
  repo:           https://github.com/finn-no/tech.finn.no/
gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-mentions
  - jekyll-paginate
