# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tech Blog
tagline:          Finn.no developer tech blog
url:              http://finn-no.github.io/tech.finn.no/
paginate:         1
paginate_path:    "page/:num"
baseurl:          "tech.finn.no/"
author:
  name:           Finn Technology
  url:            https://finn.no/
  twitter:        FINN_tech
  email:          tech@finn.no

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/finn-no/tech.finn.no
gems:
  - jekyll-redirect-from
